# Lumyrix/config/classical_ml_config/classical_ml_models.yaml

classification:
  LogisticRegression:
    module: sklearn.linear_model
    class: LogisticRegression
    pipeline:
      scaler: StandardScaler
    params:
      solver: liblinear
      penalty: l2
      C: 1.0
      random_state: 42
    tuning:
      enabled: true
      method: grid
      cv_folds: 5
      param_grid:
        penalty: ['l1', 'l2']
        C: [0.01, 0.1, 1, 10]

  RandomForest:
    module: sklearn.ensemble
    class: RandomForestClassifier
    params:
      n_estimators: 100
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
      n_jobs: -1
    tuning:
      enabled: false

  XGBoost:
    module: xgboost
    class: XGBClassifier
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      use_label_encoder: false
      eval_metric: logloss

regression:
  LinearRegression:
    module: sklearn.linear_model
    class: LinearRegression
    pipeline:
      scaler: StandardScaler
    params: {}
    tuning:
      enabled: false

  RandomForest:
    module: sklearn.ensemble
    class: RandomForestRegressor
    params:
      n_estimators: 100
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
      n_jobs: -1

  XGBoost:
    module: xgboost
    class: XGBRegressor
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42


regression:
  LinearRegression:
    module: sklearn.linear_model
    class: LinearRegression
    params: {}

  RandomForest:
    module: sklearn.ensemble
    class: RandomForestRegressor
    params:
      n_estimators: 100
      max_depth: null
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
      n_jobs: -1

  XGBoost:
    module: xgboost
    class: XGBRegressor
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42

  LightGBM:
    module: lightgbm
    class: LGBMRegressor
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: -1
      num_leaves: 31
      random_state: 42
