classification:
  LogisticRegression:
    penalty: ['l1', 'l2']
    C: [0.01, 0.1, 1, 10, 100]
    solver: ['liblinear']

  RandomForest:
    n_estimators: [50, 100, 200]
    max_depth: [None, 3, 5, 10]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['sqrt']
    bootstrap: [True, False]

  SVM:
    C: [0.01, 0.1, 1, 10, 100]
    gamma: [0.001, 0.01, 0.1, 1]
    kernel: ['rbf']

  XGBoost:
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    subsample: [0.7, 0.8, 1.0]
    colsample_bytree: [0.7, 0.8, 1.0]
    n_estimators: [100, 200]

  LightGBM:
    learning_rate: [0.01, 0.1]
    num_leaves: [31, 50, 100]
    max_depth: [-1, 5, 10]
    n_estimators: [100, 200]

regression:
  LinearRegression: {}  # No tuning for linear regression

  RandomForest:
    n_estimators: [50, 100, 200]
    max_depth: [None, 3, 5, 10]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['sqrt']
    bootstrap: [True, False]

  XGBoost:
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    subsample: [0.7, 0.8, 1.0]
    colsample_bytree: [0.7, 0.8, 1.0]
    n_estimators: [100, 200]

  LightGBM:
    learning_rate: [0.01, 0.1]
    num_leaves: [31, 50, 100]
    max_depth: [-1, 5, 10]
    n_estimators: [100, 200]
